# accounts/api_urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserProfileViewSet, AddressViewSet # Import your API ViewSets

# Initialize the DRF router for your API endpoints
router = DefaultRouter()
router.register(r'profile', UserProfileViewSet, basename='profile')
router.register(r'addresses', AddressViewSet, basename='address')

# Define URL patterns for the API
urlpatterns = [
    # This includes all URLs generated by the router (e.g., /profile/, /addresses/)
    # When included from a path like 'api/accounts/', this will make /api/accounts/profile/ work.
    path('', include(router.urls)), 
]